spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/blackjack
#    username: postgres
#    password: postgres
#    driverClassName: org.postgresql.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect



#logging:
#  level:
#      org: DEBUG