------------------------
-- Tabellen spill lager en ny rad hver gang man starter et spill.
CREATE TABLE spill
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(25) NOT NULL,
    spiller TEXT NOT NULL,
    dealer TEXT NOT NULL,
    kortstokk TEXT NOT NULL
);

ALTER TABLE spill
    ADD CONSTRAINT spill_status_check
    CHECK (status IN ('SPILLER_KAN_TREKKE_KORT', 'UAVGJORT', 'DEALER_VANT', 'SPILLER_VANT', 'BLACK_JACK'));

------------------------
-- Tabellen spiller inneholder spillerne i et spill. Spiller har et navn, men det må ikke være unikt.
-- Det er to mulige spillertyper: DEALER eller SPILLER
CREATE TABLE spiller
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spill_id BIGINT NOT NULL REFERENCES spill,
    navn varchar(100) NOT NULL,
    spillertype varchar(10) NOT NULL,
    hand varchar(200) NOT NULL
);

ALTER TABLE spiller
    ADD CONSTRAINT spiller_spillertype_check
    CHECK (spillertype IN ('DEALER', 'SPILLER'));
